# Generated by Django 5.1 on 2024-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="networkunit",
            old_name="dept",
            new_name="debt",
        ),
        migrations.AlterField(
            model_name="networkunit",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "завод"),
                    (1, "розничная сеть"),
                    (2, "индивидуальный предприниматель"),
                ],
                verbose_name="Уровень сети",
            ),
        ),
    ]
